[project]
name = "misc-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "docx>=0.2.4",
    "mypy>=1.15.0",
    "pdbpp>=0.11.6",
    "pydantic>=2.10.6",
    "pyright>=1.1.402",
    "starlette>=0.46.1",
]
